{{- if .Values.secretFiles }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authz-sql-pdp-modifier.fullname" . }}
  labels:
{{- include "authz-sql-pdp-modifier.labels" . | nindent 4 }}
stringData:
{{- range $path, $config := .Values.secretFiles }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}
